# Generated by Django 4.2.1 on 2023-06-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=255, verbose_name='sensor type')),
                ('sensor_reading', models.CharField(max_length=255, verbose_name='sensor reading')),
                ('reading_datetime', models.DateTimeField(verbose_name='reading date and time')),
                ('sensor_location', models.CharField(max_length=255, verbose_name='sensor location')),
                ('alert_threshold', models.CharField(max_length=255, verbose_name='alert threshold')),
                ('alert_message', models.TextField(blank=True, null=True, verbose_name='alert message')),
            ],
        ),
        migrations.CreateModel(
            name='VideoConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('consultation_type', models.CharField(max_length=255, verbose_name='consultation type')),
                ('prescription', models.TextField(verbose_name='prescription')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='follow-up date')),
                ('diagnosis', models.TextField(verbose_name='diagnosis')),
                ('recommendations', models.TextField(verbose_name='recommendations')),
            ],
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_datetime', models.DateTimeField(verbose_name='sent date and time')),
                ('sender', models.CharField(max_length=255, verbose_name='sender')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='attachments')),
                ('video_consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telehealth.videoconsultation')),
            ],
        ),
    ]
