# Generated by Django 4.2.1 on 2023-06-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('specialization', models.CharField(max_length=255, verbose_name='specialization')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(max_length=10, verbose_name='gender')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.TextField(verbose_name='address')),
                ('insurance_provider', models.CharField(max_length=255, verbose_name='insurance provider')),
                ('insurance_policy_number', models.CharField(max_length=255, verbose_name='insurance policy number')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('blood_pressure', models.CharField(max_length=20, verbose_name='blood pressure')),
                ('heart_rate', models.PositiveIntegerField(verbose_name='heart rate')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='temperature')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weight')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_images/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('uploaded_by', models.CharField(max_length=255, verbose_name='uploaded by')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='diagnosis')),
                ('allergies', models.TextField(verbose_name='allergies')),
                ('chronic_conditions', models.TextField(verbose_name='chronic conditions')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='test name')),
                ('test_result', models.CharField(max_length=255, verbose_name='test result')),
                ('date', models.DateField(verbose_name='date')),
                ('lab_technician', models.CharField(max_length=255, verbose_name='lab technician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('purpose', models.TextField(verbose_name='purpose')),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.medicalprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
        ),
    ]
